# Generated by Django 5.2.8 on 2025-12-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='task_planner.task'),
        ),
    ]
