# Generated by Django 5.2.8 on 2025-12-16 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0002_alter_time_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='topics',
            field=models.ManyToManyField(blank=True, to='task_planner.topic'),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='color_hex',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16777215)]),
        ),
    ]
